import { ProjectsSectionType } from "@/lib/types/sections";
import { getId, generateSlug } from "@/lib/utils/helper";

export const projectsSection: ProjectsSectionType = {
  title: "Latest Projects",
  projects: [
    {
      id: getId(),
      name: "Portfolio Website",
      url: "",
      repo: "",
      img: "/portfolio.png",
      year: 2023,
      tags: ["NextJs", "TypeScript", "TailwindCSS"],
      slug: generateSlug("Portfolio Website"),
      description: "A modern, responsive portfolio website showcasing my work and skills.",
      longDescription: "This portfolio website is built with Next.js 14, TypeScript, and TailwindCSS. It features a clean, modern design with smooth animations, dark mode support, and a fully responsive layout. The site showcases my projects, skills, experience, and provides an easy way for potential employers and clients to get in touch.",
      images: ["/portfolio.png"],
      featured: true,
    },
    {
      id: getId(),
      name: "Flair Techno Website For Eficens Systems",
      url: "https://workforce.flairtechno.com",
      repo: "",
      img: "/eficens.png",
      year: 2020,
      tags: [
        "React",
        "Java",
        "Node.js",
        "Google Cloud Platform",
        "Microservices",
        "REST APIs",
        "CI/CD",
        "CSS3",
      ],
      slug: generateSlug("Flair Techno Website For Eficens Systems"),
      description: "Enterprise workforce management platform built with microservices architecture.",
      longDescription: "A comprehensive workforce management platform developed for Eficens Systems. Built using React for the frontend and Java/Node.js for backend services, this application leverages Google Cloud Platform for scalable infrastructure. The platform features microservices architecture, RESTful APIs, and automated CI/CD pipelines for seamless deployment and updates.",
      images: ["/eficens.png"],
      featured: true,
    },
    {
      id: getId(),
      name: "Archplot",
      url: "",
      repo: "https://github.com/PraveenKusuluri08/flowdigm",
      img: "/archplot.png",
      year: 2024,
      tags: [
        "React",
        "BPMN.js",
        "Diagram Modeling",
        "Drag-and-Drop UI",
        "State Management",
        "Custom Components",
        "Canvas Rendering",
        "Workflow Automation",
        "TypeScript",
        "CSS3",
      ],
      slug: generateSlug("Archplot"),
      description: "Interactive diagram modeling tool for creating and managing workflow diagrams.",
      longDescription: "Archplot is a powerful diagram modeling application built with React and BPMN.js. It provides an intuitive drag-and-drop interface for creating complex workflow diagrams and process models. The application features custom canvas rendering, advanced state management, and a rich set of components for workflow automation. Built with TypeScript for type safety and modern CSS3 for a polished user experience.",
      images: ["/archplot.png"],
      featured: true,
    },
    {
      id: getId(),
      name: "Desi Connect",
      url: "https://github.com/PraveenKusuluri08/Desi_Connect",
      repo: "https://github.com/PraveenKusuluri08/Desi_Connect",
      img: "/desiconnect.png",
      year: 2025,
      tags: [
        "React Native",
        "Expo Router",
        "Zustand",
        "Firebase",
        "React Native Maps",
        "Expo Location",
        "NativeWind",
        "React Native Animatable",
        "Expo Vector Icons",
        "Custom Components",
      ],
      slug: generateSlug("Desi Connect"),
      description: "A social networking mobile app connecting people in local communities.",
      longDescription: "Desi Connect is a React Native mobile application built with Expo Router for seamless navigation. The app helps users connect with people in their local communities through location-based features. It integrates React Native Maps and Expo Location for geolocation services, Firebase for real-time backend services, and Zustand for efficient state management. The app features beautiful animations using React Native Animatable, custom components, and a modern UI built with NativeWind (TailwindCSS for React Native).",
      images: ["/desiconnect.png"],
      featured: true,
    },
    {
      id: getId(),
      name: "Vayam",
      url: "https://vayam-prvq.vercel.app/",
      repo: "",
      img: "/Vayam.png",
      year: 2024,
      tags: [
        "Next.js",
        "React",
        "TypeScript",
        "E-commerce",
        "Product Catalog",
        "Corporate Gifting",
        "TailwindCSS",
        "Vercel",
      ],
      slug: generateSlug("Vayam"),
      description: "Premium e-commerce platform for Gold, Diamond & Silver jewelry focused on corporate rewards and incentives.",
      longDescription: "Vayam is a comprehensive e-commerce platform specializing in premium jewelry rewards and incentives. The platform offers curated collections of Gold, Diamond, and Silver jewelry for corporate gifting, employee recognition, and personal milestones. Built with Next.js and TypeScript, the platform features a modern, responsive design with product catalogs, custom corporate gifting solutions, and seamless shopping experience. The application helps businesses build deeper connections with customers and top talent through emotionally impactful, tangible rewards that foster engagement and loyalty.",
      images: ["/Vayam.png"],
      featured: true,
    },
    {
      id: getId(),
      name: "Netflix Clone",
      url: "",
      repo: "",
      img: "/neflx.png",
      year: 2022,
      tags: [
        "React",
        "JavaScript",
        "CSS3",
        "API Integration",
        "Responsive Design",
        "Movie Streaming",
        "UI/UX",
      ],
      slug: generateSlug("Netflix Clone"),
      description: "A responsive Netflix clone with movie browsing, search functionality, and modern UI design.",
      longDescription: "A fully responsive Netflix clone application built with React and modern JavaScript. The application replicates the core features of Netflix including movie browsing, search functionality, category filtering, and a sleek user interface. Built with React for component-based architecture, the clone features responsive design that works seamlessly across all devices. The application integrates with movie APIs to fetch and display content, providing users with an authentic streaming platform experience.",
      images: ["/neflx.png"],
      featured: true,
    },
    {
      id: getId(),
      name: "Community Bartering Systems",
      url: "",
      repo: "",
      img: "/CBS.png",
      year: 2024,
      tags: [
        "React",
        "Node.js",
        "Community Platform",
        "Task Sharing",
        "Social Networking",
        "User Connections",
        "Responsive Design",
      ],
      slug: generateSlug("Community Bartering Systems"),
      description: "A community platform that helps people connect with others for simple tasks and resource sharing.",
      longDescription: "Community Bartering Systems (CBS) is a social platform designed to facilitate connections between people for simple tasks and resource sharing. The platform enables community members to share tasks, services, and resources with each other, fostering a collaborative environment. Built with modern web technologies, CBS provides an intuitive interface for users to discover opportunities, connect with neighbors, and build stronger community relationships through mutual assistance and resource exchange.",
      images: ["/CBS.png"],
      featured: true,
    },
    {
      id: getId(),
      name: "NPM Visual",
      url: "",
      repo: "https://github.com/PraveenKusuluri08/npm_visual",
      img: "/npm_visual.png",
      year: 2024,
      tags: [
        "Python",
        "Flask",
        "React",
        "TypeScript",
        "Neo4j",
        "Data Visualization",
        "Web Scraping",
        "Graph Database",
        "Package Analysis",
      ],
      slug: generateSlug("NPM Visual"),
      description: "A visualization tool that creates interactive graphs of NPM package dependencies and relationships.",
      longDescription: "NPM Visual is an innovative data visualization tool that creates interactive graphs of popular NPM packages and their relationships. The application scrapes data from various package.json files and analyzes package dependencies to identify critical insights. Built with Python Flask backend and React/TypeScript frontend, it uses Neo4j graph database to store and query complex package relationships. The tool helps identify packages that are not well maintained but heavily relied on by major companies, as well as packages with unusual licenses. This award-winning project provides developers and organizations with valuable insights into the NPM ecosystem, enabling better decision-making about package dependencies and security.",
      images: ["/npm_visual.png"],
      featured: true,
    },
  ],
};
